(begin ; TODO: Split this into smaller files?
    (test (cons? '()) #f)
    (test (cons? '(1)) #t)
    (test (cons? '(1 2)) #t)
    (test (cons? "aa") #f)
    (test (cons? 'cons?) #f)
    (test (cons? 'aaa) #f)
    (test (cons? '(1 . 2)) #t)

    (test (integer? 0) #t)
    (test (integer? -0) #t)
    (test (integer? 0.99) #f)
    (test (integer? 0.5) #f)
    (test (integer? -1e9) #t)
    (test (integer? 1e-9) #f)
    (test (integer? "aaa") #f)
    (test (integer? '()) #f)
    (test (integer? 'aaa) #f)
    (test (integer? 12316954165) #t)
    (test (integer? -61551) #t)
    
    (test (number? 0) #t)
    (test (number? -0) #t)
    (test (number? -42) #t)
    (test (number? 9999) #t)
    (test (number? 984.89494) #t)
    (test (number? -1e9) #t)
    (test (number? 1e-9) #t)
    (test (number? 'aaa) #f)
    (test (number? "aaa") #f)
    (test (number? '()) #f)

    (test (string? 42) #f)
    (test (string? "aaa") #t)
    (test (string? "") #t)
    (test (string? "This is quite a long string!") #t)
    (test (string? 'aaa) #f)
    (test (string? '()) #f)
    (test (string? #t) #f)
    (test (string? '(1 2 3)) #f)

    (test (symbol? '()) #f)
    (test (symbol? 'aaa) #t)
    (test (symbol? 'sym) #t)
    (test (symbol? 'verylongsymbol-with-special>=characters) #t)
    (test (symbol? 42) #f)
    (test (symbol? -1e9) #f)
    (test (symbol? "aaa") #f)
    (test (symbol? "") #f)
    (test (symbol? 'symbol?) #t)
    (test (symbol? symbol?) #f)

    (test (procedure? eq?) #t)
    (test (procedure? 'eq?) #f)
    (test (procedure? procedure?) #t)
    (test (procedure? 'a) #f)
    (test (procedure? test) #t)
    (test (procedure? null?) #t)
    (test (procedure? "aaa") #f)
    (test (procedure? -1e9) #f)
    (test (procedure? 'anothersym) #f)
    (test (procedure? '()) #f)
    (test (procedure? (lambda () 42)) #t)
)
