(begin
    (test (list? 42) #f)
    (test (list? 'aaa) #f)
    (test (list? -995154.684) #f)
    (test (list? "list") #f)
    (test (list? "a proper list") #f)
    (test (list? '()) #t)
    (test (list? '(1)) #t)
    (test (list? '(sym)) #t)
    (test (list? '("str")) #t)
    (test (list? '(1 2 3)) #t)
    (test (list? '(1 2 3 4 5)) #t)
    (test (list? '(1 2 (3 4) 5)) #t)
    (test (list? '(1 . 2)) #f)
    (test (list? '(1 2 3 . 4)) #f)
    (test (list? '(1 2 (3 . 4) 5)) #t)
)
